version: '3.7'
services:
  dashboard:
    build: .
    ports:
      - 443:443
    environment:
      - PER_PAGE
      - COLLECTOR_URL
      - JWT_URL
    volumes:
      - certs:/etc/ssl/dashboard/

volumes:
  certs:
